### PR TITLE
Added support for 9.71

### PR DESCRIPTION
**Pull request by buzzcloudau**
Download official client from IB. Upload to a server. Set {DOMAIN} to
the server you are hosting the jar files from.

### CODE REVIEW

**Comment by clifton** [comment]
Nice! Can you set a working default domain? Will merge if given that. Thanks!

**Comment by buzzcloudau** [comment]
I tried to find one, but couldn't. I posted this to the IB API but haven't heard back yet. If I do hear back from them I'll update my pull request.

In my own fork I pointed to localhost.

https://github.com/buzzcloudau/docker-ib-gateway

**Comment by clifton** [comment]
Hmm... do you think we should just bundle the latest IB client in the repo itself?

**Comment by buzzcloudau** [comment]
Packaging the jars and bypassing the download completely would be useful. I'd be more than happy for you to close this pull request and just update your main. The only part I would suggest copying over is the apt-get clean before update.

**Comment by buzzcloudau** [comment]
Found the correct URLs. Should be good to go now.

**Comment by buzzcloudau** [comment]
In: /bin/run-gateway
Should: socat TCP-LISTEN:4003,fork TCP:0.0.0.0:4001&
Be: socat TCP-LISTEN:4003,fork TCP:0.0.0.0:4003&

?

**Comment by clifton** [comment]
Ok, this looks good, thanks @buzzcloudau, really appreciate the work. Sorry for being late in getting back to you. I'll make you a collaborator on this repo so you can feel free to do updates yourself (but @mention me if you dont mind)

**Comment by buzzcloudau** [comment]
Thanks!

**Pull request merged**
